name: Security Scan

# To see how to reuse this workflow, see `security.yaml` workflow in this repository.

on:
  workflow_call:
    inputs:
      skip-dirs:
        description: 'comma separated list of directories where traversal is skipped'
        required: false
        type: string
        default: ''
      skip-files:
        description: 'comma separated list of files to be skipped'
        required: false
        type: string
        default: ''

jobs:
  trivy:
    name: Trivy security scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.28.0
        if: ${{ ! github.event.schedule }}  # Do not run inline checks when running periodically
        with:
          scan-type: fs
          ignore-unfixed: true
          exit-code: 1
          severity: 'HIGH,CRITICAL'
          skip-dirs: "${{ inputs.skip-dirs }}"
          skip-files: "${{ inputs.skip-files }}"
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db

      - name: Run Trivy vulnerability scanner sarif output
        uses: aquasecurity/trivy-action@0.28.0
        if: ${{ github.event.schedule }}  # Generate sarif when running periodically
        with:
          scan-type: fs
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          skip-dirs: "${{ inputs.skip-dirs }}"
          skip-files: "${{ inputs.skip-files }}"
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: ${{ github.event.schedule }}  # Upload sarif when running periodically
        with:
          sarif_file: 'trivy-results.sarif'
